#!/bin/bash

if [ -n "$*" ]; then
  docker run --name rust --rm -it -u=`id -u`:`id -g` -e CARGO_HOME=/.cargo -v $HOME/.cargo:/.cargo -v $PWD:/app -w /app rust $*
else
  docker run --name rust --rm -it rust
fi
